version: 2

sources:
   - name: raw
     database: jc-data-analytics
     schema: gz_raw_data
     loader: bigquery
     description: 'Tables from gz_raw_data dataset'
     tables:
       - name: sales
         identifier: raw_gz_sales
       - name: product
         identifier: raw_gz_product
       - name: ship
         identifier: raw_gz_ship